services:
  rabbitmq:
    image: "rabbitmq:4.1-management"
    ports: 
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: typebot
      POSTGRES_DB: sagas
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin21."
    depends_on:
      - postgres
  
  orchestrator: 
    build:
      context: ./implementation
      dockerfile: dockerfile
    command: pnpm start
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: typebot
      PG_PORT: 5432
      PG_DATABASE: sagas
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
  
  inventory:
    build:
      context: ./microservices/inventory
      dockerfile: dockerfile
    command: pnpm start
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - orchestrator
  
  invoice:
    build:
      context: ./microservices/invoice
      dockerfile: dockerfile
    command: pnpm start
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - orchestrator
 
  payment:
    build:
      context: ./microservices/payment
      dockerfile: dockerfile
    command: pnpm start
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - orchestrator
  
  shipping:
    build:
      context: ./microservices/shipping
      dockerfile: dockerfile
    command: pnpm start
    environment:
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - orchestrator

volumes: 
  rabbitmq_data:
  pg_data: